# Generated by Django 4.2.4 on 2024-05-16 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_user_task_time_modified_task_userid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='title',
            new_name='task',
        ),
    ]
